<?php

/**
 * Implements hook_entity_insert().
 */
function workbc_menu_entity_insert(\Drupal\Core\Entity\EntityInterface $entity) {

  if ($entity->getEntityTypeId() == "menu_link_content") {
    \Drupal::service('cache.render')->invalidateAll();
  }
}

/**
 * Implements hook_entity_update().
 */
function workbc_menu_entity_update(\Drupal\Core\Entity\EntityInterface $entity) {

  if ($entity->getEntityTypeId() == "menu_link_content") {
    \Drupal::service('cache.render')->invalidateAll();
  }
}

/**
 * Implements hook_entity_delete().
 */
function workbc_menu_entity_delete(\Drupal\Core\Entity\EntityInterface $entity) {

  if ($entity->getEntityTypeId() == "menu_link_content") {
    \Drupal::service('cache.render')->invalidateAll();
  }
}