<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_insert().
 */
function workbc_menu_entity_insert(EntityInterface $entity) {
  if ($entity->getEntityTypeId() === "menu_link_content") {
    \Drupal::service('cache.render')->invalidateAll();
  }
}

/**
 * Implements hook_entity_update().
 */
function workbc_menu_entity_update(EntityInterface $entity) {
  if ($entity->getEntityTypeId() === "menu_link_content") {
    \Drupal::service('cache.render')->invalidateAll();
  }
}

/**
 * Implements hook_entity_delete().
 */
function workbc_menu_entity_delete(EntityInterface $entity) {
  if ($entity->getEntityTypeId() === "menu_link_content") {
    \Drupal::service('cache.render')->invalidateAll();
  }
}

/**
 * Implements hook_responsive_menu_off_canvas_tree_alter().
 */
function workbc_menu_responsive_menu_off_canvas_tree_alter(array &$menu) {
  $splash = function(&$item) use(&$splash) {
    if (!empty($item['original_link'])) {
      $link = $item['original_link'];
      if (method_exists($link, 'getEntity') && !empty($link->getEntity()?->get('field_splash')?->value)) {
        $item['attributes']->setAttribute('data-splash', $link->getEntity()->get('field_splash')->value);
      }
    }
    foreach ($item['below'] as &$child) {
      $splash($child);
    }
  };
  foreach ($menu['#items'] as &$item) {
    $splash($item);
  }
}
