<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_insert().
 */
function workbc_menu_entity_insert(EntityInterface $entity) {
  if ($entity->getEntityTypeId() === "menu_link_content") {
    \Drupal::service('cache.render')->invalidateAll();
  }
}

/**
 * Implements hook_entity_update().
 */
function workbc_menu_entity_update(EntityInterface $entity) {
  if ($entity->getEntityTypeId() === "menu_link_content") {
    \Drupal::service('cache.render')->invalidateAll();
  }
}

/**
 * Implements hook_entity_delete().
 */
function workbc_menu_entity_delete(EntityInterface $entity) {
  if ($entity->getEntityTypeId() === "menu_link_content") {
    \Drupal::service('cache.render')->invalidateAll();
  }
}
