<?php
use Drupal\taxonomy\Entity\Term;
use Drupal\views\ViewExecutable;
use Drupal\media\Entity\Media;

/**
 * Implements hook_preprocess_views_view().
 */
function workbc_career_trek_preprocess_views_view(&$variables) {
  // Check if it's the view you want to target
  $view = $variables['view'];
  if ($view->id() == 'career_trek_redux' && $view->current_display == 'block_1') {
    $values = [];
    if ($exposed = $view->getExposedInput()) {
      $filters = $view->display_handler->getOption('filters');
      foreach ($exposed as $key => $expose) {
        if ($key === "field_skills_2_target_id") {
          foreach ($expose as $row) {
            $term = Term::load($row);
            if ($term && !empty($term->getName())) {
              $values[] = $term->getName();
            }
          }
        }
        else if ($key === "field_epbc_categories_target_id") {
          if ($expose !== 'All') foreach ((array)$expose as $row) {
            $term = Term::load($row);
            if ($term && !empty($term->getName())) {
              $values[] = $term->getName();
            }
          }
        }
        else if ($key === "field_teer_value") {
          if ($expose !== 'All') {
            $values[] = ssotTEERValues()[$expose];
          }
        }
        else if ($key === "field_region_value") {
          $title = $filters['field_region_value']['group_info']['group_items'][$expose]['title'] ?? '';
          if (!empty($title)) {
            $values[] = $title;
          }
        }
        else if ($key === "salary") {
          $min = $expose['min'] ?? '';
          $max = $expose['max'] ?? '';
          if (
            (!empty($min) || !empty($max)) &&
            (
              $min > $view->filter['field_annual_salary_value']->options['value']['min'] ||
              $max < $view->filter['field_annual_salary_value']->options['value']['max']
            )
          ) {
            if ($max >= $view->filter['field_annual_salary_value']->options['value']['max']) $max .= '+';
            $values[] = "Salary $" . $min . " - $" . $max;
          }
        } else {
          if (!empty($expose) && $key != "reset" && $key != "annual_salary_op") {
            $values[] = $expose;
          }
        }
      }
      $variables['search_view'] = array_filter($values);
    }
    $variables['view_title'] = $view->getTitle();
  }
}

/**
 * Implements hook_search_api_autocomplete_suggestions_alter().
 */
function workbc_career_trek_search_api_autocomplete_suggestions_alter(array &$suggestions, array $alter_params) {
  if (!$alter_params['query']->hasTag('career_trek_search')) return;
  foreach ($suggestions as &$suggestion) {
    $params = $suggestion->getUrl()->getRouteParameters();
    $media = Media::load($params['media']);
    if ($media && isset($media->field_noc) && isset($media->field_episode)) {
      $markup = $suggestion->getLabel() . ' (Episode ' . $media->field_episode->value . ', NOC ' . $media->field_noc->value . ')';
      $render = array(
        '#markup' => $markup
      );
      $suggestion->setRender($render);
    }
  }
}

/**
 * Implements hook_views_query_alter().
 *
 * Sorts the video library according to filter usage:
 * - If "annual_salary" filter is present, sort by salary (ASC), then by title (A–Z).
 * - Otherwise, always sort by title (A–Z) when any of the main filters are used.
 */
function workbc_career_trek_views_query_alter(ViewExecutable $view, $query) {
  if ($view->id() === 'career_trek_redux') {
    // Preload the EPBC/FYP categories.
    $epbc_tree = array_reduce(\Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree('epbc_categories'),
    function ($epbc_tree, $term) {
      if ($term->depth > 0) {
        $parent_tid = reset($term->parents);
        if (!array_key_exists($parent_tid, $epbc_tree)) {
          $epbc_tree[$parent_tid] = [];
        }
        $epbc_tree[$parent_tid][] = $term->tid;
        $epbc_tree[$term->tid] = $parent_tid;
      }
      return $epbc_tree;
    }, []);
    $salary = false;
    foreach ($query->where as &$condition_group) {
      foreach ($condition_group['conditions'] as &$condition) {
        // Adjust the salary max range to "infinite" if it's set to the upper range.
        if (is_array($condition) && str_contains($condition['field'], 'field_annual_salary_value')) {
          $salary = $condition['value'][0] !== $view->filter['field_annual_salary_value']->options['value']['min'] ||
                    $condition['value'][1] !== $view->filter['field_annual_salary_value']->options['value']['max'];

          $max =& $condition['value'][1];
          if ($max >= $view->filter['field_annual_salary_value']->options['value']['max']) {
            $max = PHP_INT_MAX;
          }
        }

        // Adjust the EPBC to child categories.
        if (is_array($condition) && str_contains($condition['field'], 'field_epbc_categories_target_id')) {
          $condition['field'] = 'field_career_videos_media_field_data__node__field_epbc_categories.field_epbc_categories_target_id';
          $condition['operator'] = 'IN';
          // If the incoming category is a parent, get all its children.
          // If it's a child, get the parent first then all its children.
          $value = reset($condition['value']);
          if (!is_array($epbc_tree[$value])) $value = $epbc_tree[$value];
          $condition['value'] = $epbc_tree[$value];
        }
      }
    }

    // Remove the salary sort if it's not used in the filters.
    if (!$salary) {
      $query->orderby = array_filter($query->orderby, function ($sort) {
        return !str_starts_with($sort['field'], 'field_career_videos_media_field_data__node__field_annual_sal');
      });
    }
  }
}

/**
*{@inheritdoc}
*/
function workbc_career_trek_theme($existing, $type, $theme, $path) {
  return [
    'career_trek_recent_jobs' => [
      'template' => 'career-trek-recent-jobs-block',
      'variables' => [
        'data' => [],
        'title' => '',
        'sub_title' => '',
        'no_of_records_to_show' => '',
        'total_result' => '',
        'no_result_text' => '',
        'readmore_label' => '',
        'jobboard_api_url_frontend' => '',
        'jobboard_api_url_backend' => '',
        'noc' => '',
        'find_job_url'=>'',
      ],
    ],
  'career_trek_video_detail' => [
      'variables' => [
        'noc' => NULL,
        'episode' => NULL,
        'node' => NULL,
        'content' => NULL,
        'view_mode' => NULL
      ],
      'template' => 'career-trek-video-detail',
    ],
  ];
}


/**
 * Implements hook_form_FORM_ID_alter().
 * Alter the exposed filter form for the Career Trek Video Library block.
 */
function workbc_career_trek_form_views_exposed_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  return;
  d('hello');
  if ($form['#id'] === 'views-exposed-form-career-trek-redux-block-1') {
    d($form);
    $clone = $form['occupational_category_api_field'];
    $clone['#group'] = "skills_collapsible";
    $terms = \Drupal::entityTypeManager()
      ->getStorage('taxonomy_term')
      ->loadTree('skills');
      $options = [];
    foreach ($terms as $term) {
      $options[$term->tid] = $term->name;
    }
    $clone['#options'] = $options;
    $form['skills'] = $clone;


    $config = \Drupal::configFactory()->getEditable('workbc_career_trek.settings');
    foreach ($form as $key => &$value) {
      $field_value = $config->get("view_" . $key . "_title");
      $field_description_value = $config->get("view_" . $key . "_description");
      if (!empty($field_value)) {
        if (isset($form[$key. '_collapsible'])) {
          $form[$key. '_collapsible']['#title'] = $field_value;
          if(isset($form[$key. '_collapsible']['#description']) && $field_description_value) {
            $form[$key. '_collapsible']['#description'] = $field_description_value;
          }
        }elseif(strpos('annual_salary_wrapper', $key) !== FALSE){
          $form[$key]['#title'] = $field_value;
          if(isset($form[$key]['#description']) && $field_description_value) {
            $form[$key]['#description'] = $field_description_value;
          }
        }
      }
      if($key == "actions") {
        if($config->get('apply_button')) {
          $form[$key]['submit']['#value'] = $config->get('apply_button');
        }
        if($config->get('apply_button')) {
          $form[$key]['reset']['#value'] = $config->get('clear_filter_button');
        }

      }
    }
  }

}

/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
function workbc_career_trek_preprocess_page(&$variables) {
  // Load the configuration.
  $config = \Drupal::config('workbc_career_trek.settings');
  // Pass the configuration values to drupalSettings.
  $settings = $config->getRawData();
  if (!empty($settings)) {
    $variables['#attached']['drupalSettings']['workbc_career_trek'] = $settings;
  }
}

