<?php

use Drupal\Core\StreamWrapper\StreamWrapperManager;
use Drupal\Core\Url;

const SSOT_ROUTES = [
  'workbc_ssot.lmmu',
  'view.ssot_log.page_1'
];

/**
 * Implements hook_file_download().
 */
function workbc_ssot_file_download($uri) {
  $scheme = StreamWrapperManager::getScheme($uri);
  $target = StreamWrapperManager::getTarget($uri);
  if ($scheme === 'private' && str_starts_with($target, 'ssot/')) {
    $filename = basename($target);
    return [
      'Content-disposition' => "attachment; filename=\"$filename\"",
    ];
  }
}

/**
 * Implements hook_element_info_alter().
 */
function workbc_ssot_element_info_alter(array &$types) {
  $types['datetime']['#process'][] = 'workbc_ssot_process_element';
}

/**
 * Element process callback for datetime fields.
 */
function workbc_ssot_process_element($element) {
  $element['time']['#attributes']['title'] = t('Enter a valid time - e.g. @format', [
    '@format' => (new \DateTime())->format('h:i'),
  ]);
  if ($element['#date_time_element'] !== 'none') {
    $element['#date_time_format'] = 'H:i';
  }
  if (!empty($element['time']['#value'])) {
    $parts = explode(':', $element['time']['#value']);
    $parts = array_splice($parts, 0, 2);
    $element['time']['#value'] = implode(':', $parts);
  }
  // Remove seconds in browsers that support HTML5 type=date.
  $element['time']['#attributes']['step'] = 60;
  return $element;
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function workbc_ssot_menu_links_discovered_alter(&$links) {
  if (empty(\Drupal::config('workbc')->get('features.ssot_upload'))) {
    foreach ($links as $key => $link) {
      if (array_key_exists('route_name', $link) && in_array($link['route_name'], SSOT_ROUTES)) {
        unset($links[$key]);
      }
    }
  }
}
