<?php

/**
 * @file
 * An example field using the Field Types API.
 */

/**
 *
 */

 function workbc_custom_theme($existing, $type, $theme, $path) {
   return [
     'related_topics_block' => [
       'variables' => [
           'related_topics' => array(
               'image' => NULL,
               'top_level_parent' => NULL,
               'title' => NULL,
               'body' => NULL,
               'action' => NULL,
           ),
       ],
     ],
     'explore_careers_block' => [
       'variables' => [
           'explore_careers' => array(
               'title' => NULL,
               'body' => NULL,
               'title_1' => NULL,
               'body_1' => NULL,
               'action_1' => NULL,
               'tooltip_1' => NULL,
               'title_2' => NULL,
               'body_2' => NULL,
               'action_2' => NULL,
           ),
       ],
     ],
   ];
 }


 /**
  * Implements hook_views_data_alter().
  */
 function workbc_custom_views_data_alter(array &$data) {


   $data['node_field_data']['workbc_nodes_granular_dates'] = [
     'title' => t('WorkBC node granular date filter'),
     'filter' => [
       'title' => t('WorkBC node granular date filter'),
       'help' => t('WorkBC node granular date filter.'),
       'field' => 'title',
       'id' => 'workbc_node_granular_date_filter',
     ],
   ];


 }
