<?php

/**
 * @file
 * An example field using the Field Types API.
 */

/**
 *
 */

  function workbc_custom_theme($existing, $type, $theme, $path) {
    return [
      'related_topics_block' => [
        'variables' => [
            'related_topics' => array(
                'image' => NULL,
                'top_level_parent' => NULL,
                'title' => NULL,
                'body' => NULL,
                'action' => NULL,
            ),
        ],
      ],
    ];
  }